<?php
//<Konfigurationsabschnitt>
define("EZSQL_DB_USER", "esniper");
define("EZSQL_DB_PASSWORD", "35n1p3r");
define("EZSQL_DB_NAME", "ebay");
define("EZSQL_DB_HOST", "localhost");
define("PATH_TO_ESNIPER", "/usr/local/bin/esniper"); //Pfad zu esniper inkl. Dateiname
define("PATH_TO_ESNIPERCONFIG", "/var/www/ebay.phobos.lan/esniper.cfg"); //Pfad zur esniper config inkl. Dateiname
define("TMP_FOLDER","/var/www/ebay.phobos.lan/tmp"); //Pfad zum temporären Ordner
//German 1
define("LANG",1);
//English 2
//</Konfigurationsabschnitt>
?>
